name: Cache-saving-test
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 13
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules          
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      - name: Install        
        run: npm i

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules          
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      - name: Run tests
        run: npm test
