name: Notifications test
on: pull_request
jobs:

  notify-test-start:
    runs-on: ubuntu-latest
    steps:
      # Get the last commit messegi inside PR
      - uses: actions/checkout@v1
      - name: get commit message
        run: |
           echo "commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - uses: bluenovaio/action-slack@main 
        with:
          text: ">*Frontend tests started*\n>for ${{ github.head_ref }} branch\n>${{ env.commitmsg }}"
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }} 

